# Generated by Django 4.0.4 on 2022-05-23 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0004_alter_experience_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ('start_date',)},
        ),
    ]
